// Metavista three.js r126 subset. Edit the member list, then run: npm run build
// Classes/objects are listed first; all numeric/string constants (tiny) follow.
import {
  MOUSE, TOUCH, EventDispatcher, Clock, Layers, Uniform, Vector2, Vector3, Vector4, Quaternion,
  Euler, Matrix3, Matrix4, Spherical, Cylindrical, Color, MathUtils, Box2, Box3, Sphere, Plane, Ray,
  Raycaster, Triangle, Frustum, Line3, SphericalHarmonics3, Object3D, Group, Scene, Mesh,
  InstancedMesh, Points, Line, LineSegments, LineLoop, Sprite, Fog, FogExp2, Camera,
  PerspectiveCamera, OrthographicCamera, CubeCamera, WebGLRenderer, WebGL1Renderer,
  WebGLRenderTarget, WebGLCubeRenderTarget, WebGLMultisampleRenderTarget, PMREMGenerator,
  ShaderChunk, ShaderLib, UniformsLib, UniformsUtils, BufferGeometry, BufferAttribute,
  Float32BufferAttribute, Float16BufferAttribute, Uint32BufferAttribute, Uint16BufferAttribute,
  Uint8BufferAttribute, Int32BufferAttribute, Int16BufferAttribute, InterleavedBuffer,
  InterleavedBufferAttribute, InstancedBufferAttribute, InstancedBufferGeometry, BoxGeometry,
  BoxBufferGeometry, PlaneGeometry, PlaneBufferGeometry, CircleGeometry, CircleBufferGeometry,
  CylinderGeometry, CylinderBufferGeometry, ConeGeometry, ConeBufferGeometry, SphereGeometry,
  SphereBufferGeometry, RingGeometry, RingBufferGeometry, TorusGeometry, TorusBufferGeometry,
  LatheGeometry, LatheBufferGeometry, ExtrudeGeometry, ExtrudeBufferGeometry, ShapeGeometry,
  ShapeBufferGeometry, TubeGeometry, TubeBufferGeometry, EdgesGeometry, Shape, Path, ShapePath,
  ShapeUtils, Curve, CurvePath, LineCurve, LineCurve3, QuadraticBezierCurve, QuadraticBezierCurve3,
  CubicBezierCurve, CubicBezierCurve3, CatmullRomCurve3, EllipseCurve, ArcCurve, SplineCurve,
  Material, MeshStandardMaterial, MeshPhysicalMaterial, MeshBasicMaterial, MeshLambertMaterial,
  MeshPhongMaterial, MeshMatcapMaterial, MeshNormalMaterial, MeshDepthMaterial, MeshDistanceMaterial,
  ShadowMaterial, ShaderMaterial, RawShaderMaterial, LineBasicMaterial, LineDashedMaterial,
  PointsMaterial, SpriteMaterial, Light, AmbientLight, DirectionalLight, HemisphereLight, PointLight,
  SpotLight, RectAreaLight, LightProbe, Texture, DataTexture, CanvasTexture, CubeTexture,
  VideoTexture, DepthTexture, Loader, LoadingManager, DefaultLoadingManager, Cache, FileLoader,
  ImageLoader, ImageBitmapLoader, TextureLoader, CubeTextureLoader, DataTextureLoader, LoaderUtils,
  DataUtils, ACESFilmicToneMapping, AddEquation, AddOperation, AdditiveAnimationBlendMode,
  AdditiveBlending, AlphaFormat, AlwaysDepth, AlwaysStencilFunc, BackSide, BasicDepthPacking,
  BasicShadowMap, ByteType, CineonToneMapping, ClampToEdgeWrapping, CubeReflectionMapping,
  CubeRefractionMapping, CubeUVReflectionMapping, CubeUVRefractionMapping, CullFaceBack,
  CullFaceFront, CullFaceFrontBack, CullFaceNone, CustomBlending, CustomToneMapping,
  DecrementStencilOp, DecrementWrapStencilOp, DepthFormat, DepthStencilFormat, DoubleSide,
  DstAlphaFactor, DstColorFactor, DynamicCopyUsage, DynamicDrawUsage, DynamicReadUsage, EqualDepth,
  EqualStencilFunc, EquirectangularReflectionMapping, EquirectangularRefractionMapping, FaceColors,
  FlatShading, FloatType, FrontSide, GLSL1, GLSL3, GammaEncoding, GreaterDepth, GreaterEqualDepth,
  GreaterEqualStencilFunc, GreaterStencilFunc, HalfFloatType, IncrementStencilOp,
  IncrementWrapStencilOp, IntType, InterpolateDiscrete, InterpolateLinear, InterpolateSmooth,
  InvertStencilOp, KeepStencilOp, LessDepth, LessEqualDepth, LessEqualStencilFunc, LessStencilFunc,
  LinePieces, LineStrip, LinearEncoding, LinearFilter, LinearMipMapLinearFilter,
  LinearMipMapNearestFilter, LinearMipmapLinearFilter, LinearMipmapNearestFilter, LinearToneMapping,
  LogLuvEncoding, LoopOnce, LoopPingPong, LoopRepeat, LuminanceAlphaFormat, LuminanceFormat,
  MaxEquation, MinEquation, MirroredRepeatWrapping, MixOperation, MultiplyBlending,
  MultiplyOperation, NearestFilter, NearestMipMapLinearFilter, NearestMipMapNearestFilter,
  NearestMipmapLinearFilter, NearestMipmapNearestFilter, NeverDepth, NeverStencilFunc, NoBlending,
  NoColors, NoToneMapping, NormalAnimationBlendMode, NormalBlending, NotEqualDepth,
  NotEqualStencilFunc, ObjectSpaceNormalMap, OneFactor, OneMinusDstAlphaFactor,
  OneMinusDstColorFactor, OneMinusSrcAlphaFactor, OneMinusSrcColorFactor, PCFShadowMap,
  PCFSoftShadowMap, REVISION, RGBADepthPacking, RGBAFormat, RGBAIntegerFormat,
  RGBA_ASTC_10x10_Format, RGBA_ASTC_10x5_Format, RGBA_ASTC_10x6_Format, RGBA_ASTC_10x8_Format,
  RGBA_ASTC_12x10_Format, RGBA_ASTC_12x12_Format, RGBA_ASTC_4x4_Format, RGBA_ASTC_5x4_Format,
  RGBA_ASTC_5x5_Format, RGBA_ASTC_6x5_Format, RGBA_ASTC_6x6_Format, RGBA_ASTC_8x5_Format,
  RGBA_ASTC_8x6_Format, RGBA_ASTC_8x8_Format, RGBA_BPTC_Format, RGBA_ETC2_EAC_Format,
  RGBA_PVRTC_2BPPV1_Format, RGBA_PVRTC_4BPPV1_Format, RGBA_S3TC_DXT1_Format, RGBA_S3TC_DXT3_Format,
  RGBA_S3TC_DXT5_Format, RGBDEncoding, RGBEEncoding, RGBEFormat, RGBFormat, RGBIntegerFormat,
  RGBM16Encoding, RGBM7Encoding, RGB_ETC1_Format, RGB_ETC2_Format, RGB_PVRTC_2BPPV1_Format,
  RGB_PVRTC_4BPPV1_Format, RGB_S3TC_DXT1_Format, RGFormat, RGIntegerFormat, RedFormat,
  RedIntegerFormat, ReinhardToneMapping, RepeatWrapping, ReplaceStencilOp, ReverseSubtractEquation,
  SRGB8_ALPHA8_ASTC_10x10_Format, SRGB8_ALPHA8_ASTC_10x5_Format, SRGB8_ALPHA8_ASTC_10x6_Format,
  SRGB8_ALPHA8_ASTC_10x8_Format, SRGB8_ALPHA8_ASTC_12x10_Format, SRGB8_ALPHA8_ASTC_12x12_Format,
  SRGB8_ALPHA8_ASTC_4x4_Format, SRGB8_ALPHA8_ASTC_5x4_Format, SRGB8_ALPHA8_ASTC_5x5_Format,
  SRGB8_ALPHA8_ASTC_6x5_Format, SRGB8_ALPHA8_ASTC_6x6_Format, SRGB8_ALPHA8_ASTC_8x5_Format,
  SRGB8_ALPHA8_ASTC_8x6_Format, SRGB8_ALPHA8_ASTC_8x8_Format, ShortType, SmoothShading,
  SrcAlphaFactor, SrcAlphaSaturateFactor, SrcColorFactor, StaticCopyUsage, StaticDrawUsage,
  StaticReadUsage, StreamCopyUsage, StreamDrawUsage, StreamReadUsage, SubtractEquation,
  SubtractiveBlending, TangentSpaceNormalMap, TriangleFanDrawMode, TriangleStripDrawMode,
  TrianglesDrawMode, UVMapping, UnsignedByteType, UnsignedInt248Type, UnsignedIntType,
  UnsignedShort4444Type, UnsignedShort5551Type, UnsignedShort565Type, UnsignedShortType,
  VSMShadowMap, VertexColors, WrapAroundEnding, ZeroCurvatureEnding, ZeroFactor, ZeroSlopeEnding,
  ZeroStencilOp, sRGBEncoding,
  Math as ThreeMath, // deprecated alias of MathUtils, kept for CDN-build compatibility
} from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';

const members = {
  Math: ThreeMath,
  MOUSE, TOUCH, EventDispatcher, Clock, Layers, Uniform, Vector2, Vector3, Vector4, Quaternion,
  Euler, Matrix3, Matrix4, Spherical, Cylindrical, Color, MathUtils, Box2, Box3, Sphere, Plane, Ray,
  Raycaster, Triangle, Frustum, Line3, SphericalHarmonics3, Object3D, Group, Scene, Mesh,
  InstancedMesh, Points, Line, LineSegments, LineLoop, Sprite, Fog, FogExp2, Camera,
  PerspectiveCamera, OrthographicCamera, CubeCamera, WebGLRenderer, WebGL1Renderer,
  WebGLRenderTarget, WebGLCubeRenderTarget, WebGLMultisampleRenderTarget, PMREMGenerator,
  ShaderChunk, ShaderLib, UniformsLib, UniformsUtils, BufferGeometry, BufferAttribute,
  Float32BufferAttribute, Float16BufferAttribute, Uint32BufferAttribute, Uint16BufferAttribute,
  Uint8BufferAttribute, Int32BufferAttribute, Int16BufferAttribute, InterleavedBuffer,
  InterleavedBufferAttribute, InstancedBufferAttribute, InstancedBufferGeometry, BoxGeometry,
  BoxBufferGeometry, PlaneGeometry, PlaneBufferGeometry, CircleGeometry, CircleBufferGeometry,
  CylinderGeometry, CylinderBufferGeometry, ConeGeometry, ConeBufferGeometry, SphereGeometry,
  SphereBufferGeometry, RingGeometry, RingBufferGeometry, TorusGeometry, TorusBufferGeometry,
  LatheGeometry, LatheBufferGeometry, ExtrudeGeometry, ExtrudeBufferGeometry, ShapeGeometry,
  ShapeBufferGeometry, TubeGeometry, TubeBufferGeometry, EdgesGeometry, Shape, Path, ShapePath,
  ShapeUtils, Curve, CurvePath, LineCurve, LineCurve3, QuadraticBezierCurve, QuadraticBezierCurve3,
  CubicBezierCurve, CubicBezierCurve3, CatmullRomCurve3, EllipseCurve, ArcCurve, SplineCurve,
  Material, MeshStandardMaterial, MeshPhysicalMaterial, MeshBasicMaterial, MeshLambertMaterial,
  MeshPhongMaterial, MeshMatcapMaterial, MeshNormalMaterial, MeshDepthMaterial, MeshDistanceMaterial,
  ShadowMaterial, ShaderMaterial, RawShaderMaterial, LineBasicMaterial, LineDashedMaterial,
  PointsMaterial, SpriteMaterial, Light, AmbientLight, DirectionalLight, HemisphereLight, PointLight,
  SpotLight, RectAreaLight, LightProbe, Texture, DataTexture, CanvasTexture, CubeTexture,
  VideoTexture, DepthTexture, Loader, LoadingManager, DefaultLoadingManager, Cache, FileLoader,
  ImageLoader, ImageBitmapLoader, TextureLoader, CubeTextureLoader, DataTextureLoader, LoaderUtils,
  DataUtils, ACESFilmicToneMapping, AddEquation, AddOperation, AdditiveAnimationBlendMode,
  AdditiveBlending, AlphaFormat, AlwaysDepth, AlwaysStencilFunc, BackSide, BasicDepthPacking,
  BasicShadowMap, ByteType, CineonToneMapping, ClampToEdgeWrapping, CubeReflectionMapping,
  CubeRefractionMapping, CubeUVReflectionMapping, CubeUVRefractionMapping, CullFaceBack,
  CullFaceFront, CullFaceFrontBack, CullFaceNone, CustomBlending, CustomToneMapping,
  DecrementStencilOp, DecrementWrapStencilOp, DepthFormat, DepthStencilFormat, DoubleSide,
  DstAlphaFactor, DstColorFactor, DynamicCopyUsage, DynamicDrawUsage, DynamicReadUsage, EqualDepth,
  EqualStencilFunc, EquirectangularReflectionMapping, EquirectangularRefractionMapping, FaceColors,
  FlatShading, FloatType, FrontSide, GLSL1, GLSL3, GammaEncoding, GreaterDepth, GreaterEqualDepth,
  GreaterEqualStencilFunc, GreaterStencilFunc, HalfFloatType, IncrementStencilOp,
  IncrementWrapStencilOp, IntType, InterpolateDiscrete, InterpolateLinear, InterpolateSmooth,
  InvertStencilOp, KeepStencilOp, LessDepth, LessEqualDepth, LessEqualStencilFunc, LessStencilFunc,
  LinePieces, LineStrip, LinearEncoding, LinearFilter, LinearMipMapLinearFilter,
  LinearMipMapNearestFilter, LinearMipmapLinearFilter, LinearMipmapNearestFilter, LinearToneMapping,
  LogLuvEncoding, LoopOnce, LoopPingPong, LoopRepeat, LuminanceAlphaFormat, LuminanceFormat,
  MaxEquation, MinEquation, MirroredRepeatWrapping, MixOperation, MultiplyBlending,
  MultiplyOperation, NearestFilter, NearestMipMapLinearFilter, NearestMipMapNearestFilter,
  NearestMipmapLinearFilter, NearestMipmapNearestFilter, NeverDepth, NeverStencilFunc, NoBlending,
  NoColors, NoToneMapping, NormalAnimationBlendMode, NormalBlending, NotEqualDepth,
  NotEqualStencilFunc, ObjectSpaceNormalMap, OneFactor, OneMinusDstAlphaFactor,
  OneMinusDstColorFactor, OneMinusSrcAlphaFactor, OneMinusSrcColorFactor, PCFShadowMap,
  PCFSoftShadowMap, REVISION, RGBADepthPacking, RGBAFormat, RGBAIntegerFormat,
  RGBA_ASTC_10x10_Format, RGBA_ASTC_10x5_Format, RGBA_ASTC_10x6_Format, RGBA_ASTC_10x8_Format,
  RGBA_ASTC_12x10_Format, RGBA_ASTC_12x12_Format, RGBA_ASTC_4x4_Format, RGBA_ASTC_5x4_Format,
  RGBA_ASTC_5x5_Format, RGBA_ASTC_6x5_Format, RGBA_ASTC_6x6_Format, RGBA_ASTC_8x5_Format,
  RGBA_ASTC_8x6_Format, RGBA_ASTC_8x8_Format, RGBA_BPTC_Format, RGBA_ETC2_EAC_Format,
  RGBA_PVRTC_2BPPV1_Format, RGBA_PVRTC_4BPPV1_Format, RGBA_S3TC_DXT1_Format, RGBA_S3TC_DXT3_Format,
  RGBA_S3TC_DXT5_Format, RGBDEncoding, RGBEEncoding, RGBEFormat, RGBFormat, RGBIntegerFormat,
  RGBM16Encoding, RGBM7Encoding, RGB_ETC1_Format, RGB_ETC2_Format, RGB_PVRTC_2BPPV1_Format,
  RGB_PVRTC_4BPPV1_Format, RGB_S3TC_DXT1_Format, RGFormat, RGIntegerFormat, RedFormat,
  RedIntegerFormat, ReinhardToneMapping, RepeatWrapping, ReplaceStencilOp, ReverseSubtractEquation,
  SRGB8_ALPHA8_ASTC_10x10_Format, SRGB8_ALPHA8_ASTC_10x5_Format, SRGB8_ALPHA8_ASTC_10x6_Format,
  SRGB8_ALPHA8_ASTC_10x8_Format, SRGB8_ALPHA8_ASTC_12x10_Format, SRGB8_ALPHA8_ASTC_12x12_Format,
  SRGB8_ALPHA8_ASTC_4x4_Format, SRGB8_ALPHA8_ASTC_5x4_Format, SRGB8_ALPHA8_ASTC_5x5_Format,
  SRGB8_ALPHA8_ASTC_6x5_Format, SRGB8_ALPHA8_ASTC_6x6_Format, SRGB8_ALPHA8_ASTC_8x5_Format,
  SRGB8_ALPHA8_ASTC_8x6_Format, SRGB8_ALPHA8_ASTC_8x8_Format, ShortType, SmoothShading,
  SrcAlphaFactor, SrcAlphaSaturateFactor, SrcColorFactor, StaticCopyUsage, StaticDrawUsage,
  StaticReadUsage, StreamCopyUsage, StreamDrawUsage, StreamReadUsage, SubtractEquation,
  SubtractiveBlending, TangentSpaceNormalMap, TriangleFanDrawMode, TriangleStripDrawMode,
  TrianglesDrawMode, UVMapping, UnsignedByteType, UnsignedInt248Type, UnsignedIntType,
  UnsignedShort4444Type, UnsignedShort5551Type, UnsignedShort565Type, UnsignedShortType,
  VSMShadowMap, VertexColors, WrapAroundEnding, ZeroCurvatureEnding, ZeroFactor, ZeroSlopeEnding,
  ZeroStencilOp, sRGBEncoding
};

// Same global shape as build/three.min.js + examples/js/controls/OrbitControls.js
window.THREE = Object.assign(window.THREE || {}, members, { OrbitControls });
